import { APP_DISPLAY_NAME } from '../../configs/constants'

const SettingType = {
  BLOCKED_USERS: 'Blocked users',
  HELP_CONTACT_US: 'Help / Contact Us',
  LEGAL_INFO: 'Legal info',
  SEND_FEEDBACK: 'Send Feedback',
  DISABLE_PROFILE: 'Disable Profile',
  CASH_OUT: 'Cash out',
  USER_INFO: 'User info',
  DELETE_ACCOUNT: 'Delete Account',
  PRIVACY_POLICY: 'Privacy Policy',
  TERM_OF_SERVICE: 'Terms of Service',
  SETTINGS: 'Settings',
  BUTTON: 'Button',
  EMAIL: 'Email',
  PASSWORD: 'Password',
  NOTIFICATION_SETTINGS: 'Notification Settings',
  LOCATION: 'Location',
  LOGOUT: 'Logout',
  CHANGE_EMAIL: 'Change your email',
  CHANGE_PASSWORD: 'Change current password',
  MANAGE_BLOCKED_LIST: 'Manage blocked users list',
  HELP_AND_SUPPORT: 'Help & support',
  LEGAL_INFORMATION: 'Legal information',
  SHARE_FEEDBACK: 'Share your feedback',
  QUESTION_ANSWER: 'Question / Answer',
  EDIT_PROFILE: 'Edit profile',
  NICKNAME: 'Nickname',
  BIO: 'Bio',
  INTERESTS: 'Interests',
  FRIENDS: 'Friends',
  FAVORITES: 'Favorites',
  REQUESTS: 'Requests',
  LIKERS: 'Liked',
  EDIT_VOICE: 'Edit voice answer',
  DISABLE_PROFILE_DESC: 'Disable or delete your profile',
  CASH_OUT_CURRENCY: 'Cash out your digital currency',
  CHANGE_PHOTO: 'Change Photo',
  UPLOAD_PHOTO: 'Upload Photo',
  SAVE: 'Save',
  EXY_USERNAME: `Your ${APP_DISPLAY_NAME} Username`,
  VERIFY_YOUR_PROFILE: 'Verify Your Profile',
  VERIFY_YOUR_PROFILE_DESC: 'Verify your profile...',
  NOTIFICATION_SETTINGS_DESC: 'In-app and push notification settings',
}

export default SettingType
