const TagType = {
  MOBILE: 'MOBILE',
  ATTACHMENT: 'ATTACHMENT',
  VIDEO_ATTACHMENT: 'VIDEO_ATTACHMENT',
  VIDEO_ATTACHMENT_RDY: 'VIDEO_ATTACHMENT_RDY',
  AUDIO_ATTACHMENT: 'AUDIO_ATTACHMENT',
  VIRTUAL_GIFT: 'VIRTUAL_GIFT',
  PRIVATE_VIDEO_CHAT: 'PRIVATE_VIDEO_CHAT',
}

export default TagType
